version: "3.9"

services:

  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"

  mumbai:
    build: .
    container_name: mumbai
    environment:
      - NODE_NAME=mumbai
      - PEERS=toxiproxy:8666,toxiproxy:8667
    ports:
      - "5001:5000"

  virginia:
    build: .
    container_name: virginia
    environment:
      - NODE_NAME=virginia
      - PEERS=toxiproxy:8668,toxiproxy:8669
    ports:
      - "5002:5000"

  frankfurt:
    build: .
    container_name: frankfurt
    environment:
      - NODE_NAME=frankfurt
      - PEERS=toxiproxy:8670,toxiproxy:8671
    ports:
      - "5003:5000"